version: '3'

services:
  streamlit-app:
    build: .
    ports:
      - "8501:8501"
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - MONGODB_DB=${MONGODB_DB:-rag_database}
      - MONGODB_COLLECTION=${MONGODB_COLLECTION:-documents}
    volumes:
      - ./app.py:/app/app.py
    restart: unless-stopped
